/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Categoria } from '../../models/categoria';

export interface Listar$Params {
}

export function listar(http: HttpClient, rootUrl: string, params?: Listar$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Categoria>>> {
  const rb = new RequestBuilder(rootUrl, listar.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<Categoria>>;
    })
  );
}

listar.PATH = '/categorias';
