/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { LancamentoRequestDto } from '../../models/lancamento-request-dto';
import { LancamentoResponseDto } from '../../models/lancamento-response-dto';

export interface Criar1$Params {
      body: LancamentoRequestDto
}

export function criar1(http: HttpClient, rootUrl: string, params: Criar1$Params, context?: HttpContext): Observable<StrictHttpResponse<LancamentoResponseDto>> {
  const rb = new RequestBuilder(rootUrl, criar1.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<LancamentoResponseDto>;
    })
  );
}

criar1.PATH = '/lancamentos';
