/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PageResponseLancamentoResponseDto } from '../../models/page-response-lancamento-response-dto';

export interface Filtrar$Params {
  descricao?: string;
  dataVencimento?: string;
  dataPagamento?: string;
  page?: number;
  size?: number;
}

export function filtrar(http: HttpClient, rootUrl: string, params?: Filtrar$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseLancamentoResponseDto>> {
  const rb = new RequestBuilder(rootUrl, filtrar.PATH, 'get');
  if (params) {
    rb.query('descricao', params.descricao, {});
    rb.query('dataVencimento', params.dataVencimento, {});
    rb.query('dataPagamento', params.dataPagamento, {});
    rb.query('page', params.page, {});
    rb.query('size', params.size, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PageResponseLancamentoResponseDto>;
    })
  );
}

filtrar.PATH = '/lancamentos';
