/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Pageable } from '../../models/pageable';
import { PageResumoLancamento } from '../../models/page-resumo-lancamento';

export interface Resumir$Params {
  descricao?: string;
  dataVencimentoDe?: string;
  dataVencimentoAte?: string;
  pageable: Pageable;
}

export function resumir(http: HttpClient, rootUrl: string, params: Resumir$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResumoLancamento>> {
  const rb = new RequestBuilder(rootUrl, resumir.PATH, 'get');
  if (params) {
    rb.query('descricao', params.descricao, {});
    rb.query('dataVencimentoDe', params.dataVencimentoDe, {});
    rb.query('dataVencimentoAte', params.dataVencimentoAte, {});
    rb.query('pageable', params.pageable, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PageResumoLancamento>;
    })
  );
}

resumir.PATH = '/lancamentos/resumir';
