/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Contato {
  codigo?: string;
  nome?: string;
  email?: string;
  telefone?: string;

}
