/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Endereco {
  bairro?: string;
  cep?: string;
  cidade?: string;
  complemento?: string;
  estado?: string;
  logradouro?: string;
  numero?: string;
}
