/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Categoria } from '../models/categoria';
import { Pessoa } from '../models/pessoa';
export interface LancamentoRequestDto {
  categoria: Categoria;
  dataPagamento?: string;
  dataVencimento: string;
  descricao: string;
  observacao?: string;
  pessoa: Pessoa;
  tipo: 'RECEITA' | 'DESPESA';
  valor: number;
}
