/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { LancamentoResponseDto } from '../models/lancamento-response-dto';
export interface PageResponseLancamentoResponseDto {
  content?: Array<LancamentoResponseDto>;
  first?: boolean;
  last?: boolean;
  number?: number;
  size?: number;
  totalElements?: number;
  totalPages?: number;
}
