/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Endereco } from '../models/endereco';
import { Contato } from '../models/contato';
export interface PessoaRequestDto {
  ativo: boolean;
  endereco: Endereco;
  nome: string;
  contatos: Array<Contato>;
}
