/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Endereco } from '../models/endereco';
export interface PessoaRequestDto {
  ativo: boolean;
  endereco: Endereco;
  nome: string;
}
