/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PessoaRequestDto } from '../../models/pessoa-request-dto';
import { PessoaResponseDto } from '../../models/pessoa-response-dto';

export interface Atualizar$Params {
  codigo: number;
      body: PessoaRequestDto
}

export function atualizar(http: HttpClient, rootUrl: string, params: Atualizar$Params, context?: HttpContext): Observable<StrictHttpResponse<PessoaResponseDto>> {
  const rb = new RequestBuilder(rootUrl, atualizar.PATH, 'put');
  if (params) {
    rb.path('codigo', params.codigo, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PessoaResponseDto>;
    })
  );
}

atualizar.PATH = '/pessoas/{codigo}';
